name: {{#snakeCase}}{{app_name}}{{/snakeCase}}
description: {{description}}

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.5.0-5.2.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  freezed_annotation: ^0.14.3
  riverpod: ^1.0.0-dev.7

dev_dependencies:
  build_runner: ^2.1.2
  flutter_gen_runner: ^3.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  # By default, the generate files are in `lib/gen/`
  output: lib/generated
